### PR TITLE
update: footer now stays at the bottom, fixed title

### LINKED ISSUE #2: Develop & Improve UI/UX

### PR DESCRIPTION
**Pull request by shashwatah**
The footer now stays at the bottom even when there is no profile being displayed. Also, I fixed a typo in the title. Issue #2

### CODE REVIEW

**Review by Safnaj — APPROVED** [review]
Great job..!

**Comment by shashwatah** [comment]
Hey, I would be grateful if you could add the "hacktoberfest-accepted" label to this PR so it can be eligible for Hacktoberfest.

**Comment by Safnaj** [comment]
> Hey, I would be grateful if you could add the "hacktoberfest-accepted" label to this PR so it can be eligible for Hacktoberfest.

Done..!

**Comment by shashwatah** [comment]
> > Hey, I would be grateful if you could add the "hacktoberfest-accepted" label to this PR so it can be eligible for Hacktoberfest.
> 
> Done..!

Thank you! 😄

**Pull request merged**
